<!---Autoøi: xmarek69, xbilid01, xgajdo24 --->
<main id="nastaveni">
<div class="content-wrapper-body">

    <h1>Nastavení</h1>
    <hr>
    <? if($zmeny_ulozeny == 1){ ?>
    <p class="info">Zmìny byli ulo¾eny</p><? } ?>
    <form method="post">
        <h2>Vyberte, které vlastnosti zbo¾í chcete ukládat:</h2>
        <table class="table" id="properties_table">
            <tr>
                <td>Název</td>
                <td>Dodavatel</td>
                <td>Nákupní cena</td>
                <td>Prodejní cena</td>
                <td>Mìrná jednotka</td>
                <td>Mno¾ství</td>
            </tr> 
            <tr>
                <td><input type="checkbox" name="nazev" value="checked" <?= $checked['nazev'] ?>></td>
                <td><input type="checkbox" name="dodavatel" value="checked" <?= $checked['dodavatel'] ?>></td>
                <td><input type="checkbox" name="cena_nakupni" value="checked" <?= $checked['cena_nakupni'] ?>></td>
                <td><input type="checkbox" name="cena_prodejni" value="checked" <?= $checked['cena_prodejni'] ?>></td>
                <td><input type="checkbox" name="mj" value="checked" <?= $checked['mj'] ?>></td>
                <td><input type="checkbox" name="mnozstvi" value="checked" <?= $checked['mnozstvi'] ?>></td>
            </tr>  
        </table>
        
        <input class="btn btn-secondary" type="submit" name="save" value="Ulo¾it">
    </form>
</div>
</main>