<!---Autoři: xmarek69, xbilid01, xgajdo24 --->
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta http-equiv="content-type" content="text/html;" charset="ISO-8859-2"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="css/styles.css">
    <title>Inventory manager</title>
</head>
<body>
    <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
</body>
</html>